#!/usr/bin/env sh

# bar settings
yabai -m config status_bar                   on
yabai -m config status_bar_text_font         "Helvetica Neue:Regular:13.0"
yabai -m config status_bar_icon_font         "Iosevka Nerd Font:Medium:12.0"
yabai -m config status_bar_background_color  0xff202020
yabai -m config status_bar_foreground_color  0xffa8a8a8
yabai -m config status_bar_space_icon_strip  I II III IV V VI VII VIII IX X
yabai -m config status_bar_power_icon_strip   
yabai -m config status_bar_space_icon        
yabai -m config status_bar_clock_icon        

# window modifications
yabai -m config window_topmost               on
yabai -m config window_shadow                on
yabai -m config window_opacity               on

yabai -m config window_border                on
yabai -m config active_window_border_color   0xff2979ff
yabai -m config normal_window_border_color   0xff9e9e9e
yabai -m config insert_window_border_color   0xff00e676
yabai -m config window_border_width          1
yabai -m config window_border_radius         0

yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off

# mouse support
yabai -m config mouse_modifier               cmd
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config focus_follows_mouse autoraise

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  8
yabai -m config bottom_padding               8
yabai -m config left_padding                 8
yabai -m config right_padding                8
yabai -m config window_gap                   8

yabai -m config --space 4 layout             float
yabai -m rule --add app=Notes space=3
yabai -m rule --add app=Safari space=2

# automation with rules and signals
yabai -m rule --add app="^System Preferences$" manage=off

echo "yabai configuration loaded.."
